#!/bin/bash

package=rtpengine
name=rtpengine
version="4.4.0"
isadded=`dkms status -m "$name" -v "$version"`

if [ "x${isadded}" = "x" ] ; then
	dkms add -m "$name" -v "$version"
fi

if [ "$1" = 'configure' ] ; then
	dkms build -m "$name" -v "$version" && dkms install -m "$name" -v "$version" || true
fi

grep xt_RTPENGINE /etc/modules &>/dev/null
if [ $? -ne 0 ]; then
    echo xt_RTPENGINE >> /etc/modules
fi

:
