#!/bin/sh

set -e

package=rtpengine
name=rtpengine

version=`dpkg-query -W -f='${Version}' "$package" \
        |rev|cut -d- -f2-|rev|cut -d':' -f2|tr -d "\n"`

# make sure it's not running
if [ -x /etc/init.d/rtpengine ] ; then
	invoke-rc.d rtpengine stop || true
fi

dkms remove -m "$name" -v "$version" --all || true

:
