#!/bin/bash

package=rtpengine
name=rtpengine
version=4.4.0

# make sure it's not running
if [ -x /etc/init.d/rtpengine ] ; then
	systemctl rtpengine stop || true
fi

dkms remove -m "$name" -v "$version" --all || true

:
